name: Scrape Minerva Data and Post to Discord

on:
  schedule:
    - cron: '0 12 * * *'  # This will run at 12:00 PM UTC every day. Modify as needed.
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'  # Specify your Go version here

    - name: Install dependencies
      run: go mod tidy

    - name: Run the Go scraper
      run: go run main.go
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Store your Discord webhook URL in GitHub Secrets
