name: Scrape Minerva Data and Post to Discord

on:
  schedule:
    - cron: '0 12 * * *'  # This will run at 12:00 PM UTC every day. Modify as needed.
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tor and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y tor jq
        sudo service tor start

    - name: Verify Tor is running
      run: |
        # Verify Tor is running on the correct port (9050 for SOCKS5)
        ps aux | grep tor
        netstat -an | grep 9050

    - name: Wait for Tor to be ready
      run: |
        # Wait for Tor to be fully initialized and listening on port 9050
        while ! nc -z 127.0.0.1 9050; do
          echo "Waiting for Tor to be ready..."
          sleep 1
        done
        echo "Tor is ready!"
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'  # Specify your Go version here

    - name: Install dependencies
      run: go mod tidy

    - name: Run the Go scraper
      run: go run main.go
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Store your Discord webhook URL in GitHub Secrets