name: Scrape Minerva Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.4'

      - name: Install Tor and required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y tor jq netcat
          sudo service tor start

      - name: Verify Tor is running
        run: |
          ps aux | grep tor
          netstat -an | grep 9050

      - name: Wait for Tor to be ready
        run: |
          while ! nc -z 127.0.0.1 9050; do
            echo "Waiting for Tor to be ready..."
            sleep 1
          done
          echo "Tor is ready!"
          
      - name: Run Scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: go run main.go
        continue-on-error: true

      - name: Retry on failure
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.name,
              workflow_id: context.workflow,
              ref: context.ref
            })

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
